### ISSUE TITLE
Add a new metadata field

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ucsb-camp-sufia#1]

**Comment by ilessing** [comment]
Mark Suggests looking in the syllabus about Managing your descriptive metadata for clues on how to do this.

**Comment by thatbudakguy** [comment]
using metadata customization tutorial from [the Sufia wiki](https://github.com/projecthydra/sufia/wiki/Customizing-Metadata).

**Comment by thatbudakguy** [comment]
this is nontrivial as the tutorials are based on some classes/terminology not used in Sufia 7. shelving for now.
