### ISSUE TITLE
Change the home page banner image.

### ISSUE THREAD

**Issue by jeremymcwilliams** [curationexperts/ucsb-camp-sufia#9]
Use this one instead, available here: https://www.ecommerceventure.com/files/site-wide-banner.jpg

![site-wide-banner](https://cloud.githubusercontent.com/assets/1103262/13304884/5a2425f6-db0c-11e5-8196-3e6080805353.jpg)

**Comment by jeremymcwilliams** [comment]
Success, I think. Did the following:
--updated app/assets/stylesheets/application.css

`#home_header  {
    background-image: url('site-wide-banner.jpg') !important ;

}`
--added site-wide-banner.jpg to app/assets/images/

![screen shot 2016-02-24 at 4 42 04 pm](https://cloud.githubusercontent.com/assets/1103262/13306105/94f837cc-db15-11e5-8ffd-9b86c24cd882.png)

**Comment by jeremymcwilliams** [comment]
Got rid of !important by changing order of styles being loaded:

 *= require sufia
 *= require_tree .
 *= require_self

**Comment by thatbudakguy** [comment]
resolved by #11
